### ISSUE TITLE
Lab schedule

### ISSUE THREAD

**Issue by poptar7** [RIT-CSEC-Labs/Miscellaneous-Issues#1]
The lab schedule currently does not load, as such it is also not being displayed on the monitors.

**Comment by ew0k** [comment]
The lab schedule found at [this link](https://csec-labops.igm.rit.edu/public/display/?id=32) does load on a traditional computer for both Chrome and Firefox, but not on a phone. This is expected behavior as mobile is unfortunately not supported. I will make separate issues to fix the lab displays.
